In [1]:
import numpy

In [2]:
a=numpy.array([1,2,3,4,5,6,7,8])

In [3]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
b=numpy.array([44,66,88,33,22])

In [5]:
b

array([44, 66, 88, 33, 22])

In [6]:
b.shape

(5,)

In [7]:
a.shape

(8,)

In [8]:
import numpy as np
d=np.array([3,77,55,4,8,34])

In [9]:
d

array([ 3, 77, 55,  4,  8, 34])

In [10]:
d.shape

(6,)

In [11]:
import numpy as np
s=np.array([45,67,89,23,12,90,34,69])

In [12]:
s

array([45, 67, 89, 23, 12, 90, 34, 69])

In [13]:
s.shape

(8,)

In [14]:
a=np.array([[1,2],[3,4]])

In [15]:
a

array([[1, 2],
       [3, 4]])

In [16]:
a.shape

(2, 2)

In [17]:
b=np.array([[3,4],[5,7]])

In [18]:
b

array([[3, 4],
       [5, 7]])

In [19]:
b.shape

(2, 2)

In [20]:
c=np.array([[1,2,3],[4,5,6]])

In [21]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
c.shape

(2, 3)

In [23]:
d=np.array([[2,3,4],[5,6,7],[8,9,1]])

In [24]:
d

array([[2, 3, 4],
       [5, 6, 7],
       [8, 9, 1]])

In [25]:
d.shape

(3, 3)

In [26]:
e=np.array([[1,2],[3,4],[5,6]])

In [27]:
e

array([[1, 2],
       [3, 4],
       [5, 6]])

In [28]:
e.shape

(3, 2)

In [29]:
x=np.array([[34,56,21],[45,44,90],[54,89,12],[33,22,88]])

In [30]:
x

array([[34, 56, 21],
       [45, 44, 90],
       [54, 89, 12],
       [33, 22, 88]])

In [31]:
x.shape

(4, 3)

In [32]:
y=np.array([[23,56,90,65],[12,23,34,45],[56,67,78,89],[89,90,87,65]])

In [33]:
y

array([[23, 56, 90, 65],
       [12, 23, 34, 45],
       [56, 67, 78, 89],
       [89, 90, 87, 65]])

In [34]:
y.shape

(4, 4)

In [35]:
y.min()

12

In [36]:
y.max()

90

In [37]:
y.size

16

In [38]:
a.size

4

In [39]:
b.size

4

In [40]:
c.size

6

In [41]:
d.size

9

In [42]:
e.size

6

In [43]:
x.size

12

In [44]:
a.itemsize

4

In [45]:
y.itemsize

4

In [46]:
y.dtype

dtype('int32')

In [47]:
x.dtype

dtype('int32')

In [48]:
e.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
x=np.arange(20)

In [51]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [52]:
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [53]:
z=np.arange(30)
print(z)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [56]:
a=z.reshape(5,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [59]:
s=np.arange(40).reshape(5,8)

In [60]:
s

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [61]:
type(y)

numpy.ndarray

In [62]:
import numpy as np
f=np.array([[2,3,4],[5,6,7],[8,9,7]],dtype='float32')
f

array([[2., 3., 4.],
       [5., 6., 7.],
       [8., 9., 7.]], dtype=float32)

In [63]:
#ravel where you can convert one numpy array into a single row
print(f.ravel())

[2. 3. 4. 5. 6. 7. 8. 9. 7.]


In [64]:
g=np.array([[2,3,4],[5,6,7],[7,8,9]])
g

array([[2, 3, 4],
       [5, 6, 7],
       [7, 8, 9]])

In [65]:
g.shape

(3, 3)

In [66]:
print(g.ravel())
g

[2 3 4 5 6 7 7 8 9]


array([[2, 3, 4],
       [5, 6, 7],
       [7, 8, 9]])

In [67]:
print(g.ravel())

[2 3 4 5 6 7 7 8 9]


In [68]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [69]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [70]:
np.empty((2,2))

array([[1.21144843e-305, 3.82368608e-297],
       [2.50691535e-292, 7.01468486e-292]])

In [73]:
import numpy as np
w=np.array([[2,3,4],[3,4,5],[6,7,8],[9,1,2]])
w

array([[2, 3, 4],
       [3, 4, 5],
       [6, 7, 8],
       [9, 1, 2]])

In [74]:
w.shape

(4, 3)

In [75]:
w.reshape(3,4)

array([[2, 3, 4, 3],
       [4, 5, 6, 7],
       [8, 9, 1, 2]])

In [76]:
w.size

12

In [77]:
w.itemsize

4

In [79]:
w.dtype

dtype('int32')

In [80]:
import numpy as np
q=np.array([[22,33,44],[44,55,66]])
print(q)

[[22 33 44]
 [44 55 66]]


In [81]:
q.shape

(2, 3)

In [82]:
q.reshape(3,2)

array([[22, 33],
       [44, 44],
       [55, 66]])

In [85]:
p=np.arange(27)

In [86]:
p

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [87]:
print(p)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


In [95]:
r=np.arange(30).reshape(5,6)
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [96]:
r.size

30

In [97]:
r.itemsize

4

In [98]:
r.dtype

dtype('int32')

In [103]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [104]:
np.arange(4,30,2)

array([ 4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [106]:
a=np.array([[2,3,4],[5,6,7]])
b=np.array([[4,5,6],[7,8,9]])
print(a)
print(b)

[[2 3 4]
 [5 6 7]]
[[4 5 6]
 [7 8 9]]


In [107]:
a=np.array([[2,3,4]])
b=np.array([[4,5,6]])
print(a)
print(b)
            

[[2 3 4]]
[[4 5 6]]


In [108]:
c-a-b
print(c)

[[1 2 3]
 [4 5 6]]


In [109]:
c=a-b
print(c)

[[-2 -2 -2]]


In [110]:
b**2

array([[16, 25, 36]], dtype=int32)

In [111]:
a**2

array([[ 4,  9, 16]], dtype=int32)

In [115]:
h=np.random.random((2,3))
print(h)

[[0.86851114 0.65317672 0.54046221]
 [0.10140412 0.13870304 0.22072232]]


universal functions

In [117]:
a=np.arange(3)
a

array([0, 1, 2])

In [118]:
np.exp(a)

array([1.        , 2.71828183, 7.3890561 ])

In [119]:
np.sqrt(a)

array([0.        , 1.        , 1.41421356])

In [121]:
c=np.array([2,3,4])
np.add(b,c)

array([[ 6,  8, 10]])

indexing slicing iteration

In [124]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [125]:
a[2]

2

In [126]:
a[4]

4

In [127]:
a[1]

1

slicing

In [128]:
a[2:5]

array([2, 3, 4])

In [129]:
a[3:6]

array([3, 4, 5])

In [130]:
a[6:8]

array([6, 7])

In [131]:
a[-1]

9

In [132]:
a[-5]

5

In [133]:
a[-4:]

array([6, 7, 8, 9])

In [134]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [135]:
a[4:]

array([4, 5, 6, 7, 8, 9])

In [136]:
a[:-4]

array([0, 1, 2, 3, 4, 5])

In [137]:
a[:4]

array([0, 1, 2, 3])

In [138]:
a[-4:-2]

array([6, 7])

In [139]:
a[-6:-2]

array([4, 5, 6, 7])

In [140]:
a[-5:-1]

array([5, 6, 7, 8])

In [141]:
a[-5]

5

In [142]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [143]:
a[4:5]

array([4])

In [144]:
a[2:6]

array([2, 3, 4, 5])

In [145]:
d1=np.arange(30)

In [146]:
d1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [147]:
d1[5:]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29])

In [148]:
d3=np.array([np.nan,1,2,3,4,np.nan,6,7,8])
d3

array([nan,  1.,  2.,  3.,  4., nan,  6.,  7.,  8.])

In [149]:
print(d3[~np.isnan(d3)])

[1. 2. 3. 4. 6. 7. 8.]


In [150]:
np.random.rand(2,3)

array([[0.51503733, 0.34977017, 0.77065175],
       [0.05990984, 0.75073048, 0.60719831]])

In [151]:
np.random.randn(3,2)

array([[ 0.98356498,  0.67863258],
       [ 2.12515429,  0.36065255],
       [ 0.25070849, -0.28800311]])

In [152]:
np.random.randn(2,3)

array([[-0.1877957 ,  0.31497043,  0.49863384],
       [ 1.62344841,  0.15148485, -0.48797822]])