In [2]:
import scipy
import scipy.stats as sp
import numpy as np
import warnings
warnings.filterwarnings("ignore")

scipy.__version__

'1.5.2'

In [9]:
a=np.array([[3,7,5],[2,5,7],[8,9,3]])
a

array([[3, 7, 5],
       [2, 5, 7],
       [8, 9, 3]])

In [10]:
print(scipy.mean(a))

5.444444444444445


In [11]:
print(scipy.median(a))

5.0


In [12]:
print(scipy.var(a))

5.3580246913580245


In [13]:
print(scipy.std(a))

2.3147407395555177


In [14]:
a

array([[3, 7, 5],
       [2, 5, 7],
       [8, 9, 3]])

In [17]:
import scipy.stats as st
print(st.mode(a))

ModeResult(mode=array([[2, 5, 3]]), count=array([[1, 1, 1]]))


In [19]:
import pandas as pd
df=pd.read_csv('student_marks.csv')
df.head()

Unnamed: 0 Gender         DOB  Maths  Physics  Chemistry  English  Biology  \
0       John      M  05-04-1988     55       45         56       87       21   
1     Suresh      M  04-05-1987     75       96         78       64       90   
2     Ramesh      M  25-05-1989     25       54         89       76       95   
3    Jessica      F  12-08-1990     78       96         86       63       54   
4   Jennifer      F  02-09-1989     58       96         78       46       96   

   Economics  History  Civics  
0         52       89      65  
1         61       58       2  
2         87       56      74  
3         89       75      45  
4         77       83      53

In [20]:
df['Maths'].mean()

59.6

In [21]:
df['English'].mean()

69.7

In [22]:
df['Maths'].median()

55.0

In [23]:
df['Chemistry'].mean()

75.3

In [26]:
df['Physics'].median()

70.0

In [27]:
df['Civics'].mode()

0     2
1    45
2    52
3    53
4    61
5    65
6    74
7    77
8    87
9    89
dtype: int64

In [28]:
df['Physics'].mode()

0    96
dtype: int64

In [29]:
df.describe()

Maths    Physics  Chemistry    English    Biology  Economics  \
count  10.000000  10.000000  10.000000  10.000000  10.000000  10.000000   
mean   59.600000  72.300000  75.300000  69.700000  64.700000  72.700000   
std    19.460501  20.661559  14.000397  14.453373  26.998148  14.629119   
min    25.000000  45.000000  52.000000  46.000000  21.000000  52.000000   
25%    54.250000  56.250000  65.000000  59.250000  54.250000  58.750000   
50%    55.000000  70.000000  78.000000  69.500000  66.500000  76.000000   
75%    70.750000  93.750000  86.750000  81.250000  87.000000  86.000000   
max    96.000000  96.000000  89.000000  89.000000  96.000000  89.000000   

         History   Civics  
count  10.000000  10.0000  
mean   69.700000  60.5000  
std    14.453373  25.3432  
min    46.000000   2.0000  
25%    59.250000  52.2500  
50%    69.500000  63.0000  
75%    81.250000  76.2500  
max    89.000000  89.0000

PERCENTILE AND SPREAD OF DATA

In [30]:
import scipy
from scipy import stats
from scipy.stats import percentileofscore

In [31]:
percentileofscore(df['Maths'],25)

10.0

In [33]:
percentileofscore(df['English'],60)

30.0

In [34]:
percentileofscore(df['Biology'],60)

50.0

In [36]:
max_m=df['Maths'].max()
max_m

96

In [38]:
min_m=df['Maths'].min()
min_m

25

In [39]:
r=max_m-min_m

In [40]:
r

71

SPREAD OF DATA

Q1 Q2 Q3

IQR = INTERQUANTILE = Q3-Q1

In [44]:
q1=df['Maths'].quantile(0.25)
q1

54.25

In [47]:
q3=df['Maths'].quantile(0.75)
q3

70.75

In [49]:
IQR=q3-q1
IQR

16.5

In [50]:
df['Maths'].var()

378.71111111111105

In [51]:
df['Maths'].std()

19.46050130677807

In [52]:
print(df['Maths'].var())
print(df['Maths'].std())

378.71111111111105
19.46050130677807


In [53]:
print(df['English'].var())
print(df['English'].std())

208.89999999999998
14.453373308677804


In [54]:
print(df['Physics'].var())
print(df['Physics'].std())

426.8999999999999
20.661558508495915


In [55]:
from scipy.stats import zscore

In [56]:
zscore([56,34,78,90])

array([-0.39685411, -1.42400594,  0.63029771,  1.19056234])

In [57]:
df.iloc[:,3:-1]

Maths  Physics  Chemistry  English  Biology  Economics  History
0     55       45         56       87       21         52       89
1     75       96         78       64       90         61       58
2     25       54         89       76       95         87       56
3     78       96         86       63       54         89       75
4     58       96         78       46       96         77       83
5     45       87         52       89       55         89       87
6     55       64         61       58       75         58       64
7     54       76         87       56       25         56       76
8     55       63         89       75       78         75       63
9     96       46         77       83       58         83       46

In [58]:
df.iloc[:,3:10]

Maths  Physics  Chemistry  English  Biology  Economics  History
0     55       45         56       87       21         52       89
1     75       96         78       64       90         61       58
2     25       54         89       76       95         87       56
3     78       96         86       63       54         89       75
4     58       96         78       46       96         77       83
5     45       87         52       89       55         89       87
6     55       64         61       58       75         58       64
7     54       76         87       56       25         56       76
8     55       63         89       75       78         75       63
9     96       46         77       83       58         83       46